# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('color', models.CharField(default='Blue', max_length=30, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TsheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('starthr', models.PositiveSmallIntegerField(verbose_name='starthr')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='hours')),
                ('client', models.CharField(max_length=30, verbose_name='client')),
                ('jobtype', models.CharField(max_length=30, verbose_name='jobtype')),
                ('employee', models.IntegerField(verbose_name='employee')),
            ],
        ),
    ]
