# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsheetentry',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='description'),
        ),
    ]
