# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_tsheetentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='is_miscellaneous',
            field=models.BooleanField(default=False, verbose_name='is_miscellaneous'),
        ),
    ]
