# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_jobtype_is_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Timesheet entries are saved by name hence change/delete only when entries corresponding to this client are not needed', max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='is_miscellaneous',
            field=models.BooleanField(default=False, help_text="Forces the client to become 'Miscellaneous' when this job is chosen", verbose_name='Miscellaneous'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
    ]
