# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20160407_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active clients will be shown while marking hours', verbose_name='Active'),
        ),
    ]
