# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import timecapture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name': 'TimeUser',
                'abstract': False,
                'verbose_name_plural': 'TimeUsers',
                'db_table': 'timeuser',
            },
            managers=[
                ('objects', timecapture.models.TimeUserManager()),
            ],
        ),
    ]
