# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapture', '0004_auto_20160306_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='timeuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
    ]
