# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecapture', '0005_auto_20160306_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeuser',
            name='is_staff',
        ),
    ]
