# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecapture', '0006_remove_timeuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
